#!/bin/bash


usage() { echo "Usage: $0 [-h <4host>]" 1>&2; exit 1; }

while getopts ":h:" o; do
    case "${o}" in
        h)
            host=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${host}" ]; then
    usage
fi

if [ -f "machines.d/${host}.yaml" ]; then
    echo "Using machines.d/${host}.yaml"
    wget https://raw.github.com/coreos/init/master/bin/coreos-install
    chmod +x coreos-install
    sudo ./coreos-install -d /dev/sda -C stable -c machines.d/${host}.yaml
else
    echo "Machine not configured machines.d/${host}.yaml"
fi
